# Generated by Django 2.2.4 on 2019-08-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190824_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', upload_to='post_images'),
        ),
    ]
