# Generated by Django 2.2.4 on 2019-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190824_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='post_images/default.jpg', upload_to='post_images'),
        ),
    ]
