# Generated by Django 2.2.4 on 2019-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190829_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='static/images/logo.png', upload_to='post_images'),
        ),
    ]
