# Generated by Django 2.2.4 on 2019-09-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190829_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='G:\\python-projects\\Blog\\env\\mysite\\static\\images\\logo.jpg', upload_to='post_images'),
        ),
    ]
