# Generated by Django 2.2.4 on 2019-09-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190902_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='static\\images\\logo.jpg', upload_to='post_images'),
        ),
    ]
